# Generated by Django 5.2.3 on 2026-09-01 11:19

import django.db.models.deletion
import loyalty.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0006_appointment_appointment_number_and_more'),
        ('main', '0023_service_short_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CareFirst Smile Rewards', max_length=150, verbose_name='Program Name')),
                ('tagline', models.CharField(default='Your care deserves a little extra.', max_length=255, verbose_name='Program Tagline')),
                ('description', models.TextField(blank=True, default='Complete eligible dental visits and unlock exclusive savings on your care without any app or membership cards required.', verbose_name='Description')),
                ('required_completed_treatments', models.PositiveIntegerField(default=3, help_text='Number of eligible completed treatments needed to unlock a reward (e.g. 3)', verbose_name='Required Completed Visits')),
                ('reward_type', models.CharField(choices=[('percentage', 'Percentage Discount (e.g. 10% OFF)'), ('fixed_amount', 'Fixed Amount Discount (e.g. NPR 1,000 OFF)'), ('free_service', 'Free Preventive Service / Checkup')], default='percentage', max_length=30, verbose_name='Reward Type')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage discount given when reward is unlocked (e.g. 10.00)', max_digits=5, verbose_name='Discount Percentage (%)')),
                ('fixed_discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Used if reward type is fixed amount', max_digits=10, verbose_name='Fixed Discount Amount (NPR)')),
                ('maximum_discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Set to 0 for unlimited discount', max_digits=10, verbose_name='Maximum Discount Cap (NPR)')),
                ('expiry_days', models.PositiveIntegerField(default=60, help_text='Number of days unlocked rewards remain valid before expiring', verbose_name='Reward Validity Period (Days)')),
                ('allow_all_services_by_default', models.BooleanField(default=True, help_text='If checked, all clinic services count towards rewards unless explicitly excluded.', verbose_name='All Services Eligible by Default')),
                ('allow_consultations_eligible', models.BooleanField(default=False, help_text='Usually set to False to count only clinical treatment visits.', verbose_name='Count Free/Basic Consultations as Eligible Visits')),
                ('is_active', models.BooleanField(default=True, verbose_name='Program Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_services', models.ManyToManyField(blank=True, related_name='eligible_loyalty_programs', to='main.service', verbose_name='Explicitly Eligible Services')),
                ('excluded_services', models.ManyToManyField(blank=True, related_name='excluded_loyalty_programs', to='main.service', verbose_name='Excluded Services / Materials')),
            ],
            options={
                'verbose_name': 'Loyalty Program',
                'verbose_name_plural': 'Loyalty Programs',
            },
        ),
        migrations.CreateModel(
            name='PatientLoyaltyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Patient ID')),
                ('phone', models.CharField(db_index=True, max_length=30, verbose_name='Registered Phone Number')),
                ('normalized_phone', models.CharField(db_index=True, max_length=30, verbose_name='Normalized Phone')),
                ('full_name', models.CharField(max_length=200, verbose_name='Patient Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('current_progress', models.PositiveIntegerField(default=0, help_text='Current count of completed eligible treatments in active cycle (e.g. 1 of 3)', verbose_name='Current Cycle Progress')),
                ('current_cycle', models.PositiveIntegerField(default=1, help_text='Increments every time a reward is unlocked (e.g. Cycle 1, Cycle 2)', verbose_name='Current Reward Cycle')),
                ('total_completed_eligible_treatments', models.PositiveIntegerField(default=0, verbose_name='Lifetime Completed Treatments')),
                ('total_rewards_earned', models.PositiveIntegerField(default=0, verbose_name='Total Rewards Earned')),
                ('total_rewards_redeemed', models.PositiveIntegerField(default=0, verbose_name='Total Rewards Redeemed')),
                ('notes', models.TextField(blank=True, verbose_name='Reception / Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profiles', to='loyalty.loyaltyprogram', verbose_name='Enrolled Program')),
            ],
            options={
                'verbose_name': 'Patient Loyalty Profile',
                'verbose_name_plural': 'Patient Loyalty Profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(blank=True, max_length=200, verbose_name='Treatment Description')),
                ('invoice_reference', models.CharField(blank=True, max_length=100, verbose_name='Invoice / Receipt Ref')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid (NPR)')),
                ('transaction_type', models.CharField(choices=[('treatment_completed', 'Eligible Treatment Completed (+1 Progress)'), ('reward_unlocked', 'Reward Unlocked (Cycle Reset)'), ('reward_applied', 'Reward Applied to Invoice'), ('reward_expired', 'Reward Expired'), ('reward_cancelled', 'Reward Cancelled / Overridden'), ('admin_adjustment', 'Staff Manual Adjustment')], max_length=40, verbose_name='Action Type')),
                ('progress_added', models.IntegerField(default=0, verbose_name='Progress Added (+/-)')),
                ('notes', models.TextField(blank=True, verbose_name='Audit Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='appointments.appointment', verbose_name='Related Appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Staff User')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyprogram', verbose_name='Program')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service', verbose_name='Clinical Service')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.patientloyaltyprofile', verbose_name='Patient Profile')),
            ],
            options={
                'verbose_name': 'Loyalty Transaction',
                'verbose_name_plural': 'Loyalty Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_reference', models.CharField(db_index=True, default=loyalty.models.generate_reward_reference, max_length=50, unique=True, verbose_name='Reward Reference ID')),
                ('reward_type', models.CharField(choices=[('percentage', 'Percentage Discount (e.g. 10% OFF)'), ('fixed_amount', 'Fixed Amount Discount (e.g. NPR 1,000 OFF)'), ('free_service', 'Free Preventive Service / Checkup')], default='percentage', max_length=30)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Discount %')),
                ('fixed_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fixed Discount (NPR)')),
                ('maximum_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Max Discount Cap (NPR)')),
                ('status', models.CharField(choices=[('available', 'Available (Ready for Use)'), ('applied', 'Applied to Invoice'), ('expired', 'Expired'), ('cancelled', 'Cancelled by Staff')], db_index=True, default='available', max_length=20, verbose_name='Status')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Unlocked At')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires At')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Redeemed At')),
                ('applied_invoice_ref', models.CharField(blank=True, max_length=100, verbose_name='Applied Invoice / Bill Ref')),
                ('discount_amount_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Calculated Discount (NPR)')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation / Override Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_loyalty_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Staff Who Applied Reward')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='loyalty.loyaltyprogram', verbose_name='Program')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='loyalty.patientloyaltyprofile', verbose_name='Patient Profile')),
            ],
            options={
                'verbose_name': 'Loyalty Reward',
                'verbose_name_plural': 'Loyalty Rewards',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email Notification'), ('whatsapp', 'WhatsApp Message'), ('sms', 'SMS Text')], db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('progress_update', 'Progress Update (1/3, 2/3)'), ('reward_unlocked', 'Reward Unlocked (3/3)'), ('reward_applied', 'Reward Redeemed Confirmation'), ('reward_reminder', 'Reward Expiry Reminder')], db_index=True, max_length=30)),
                ('recipient', models.CharField(max_length=150, verbose_name='Recipient (Phone / Email)')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('message_body', models.TextField(verbose_name='Message Content')),
                ('status', models.CharField(choices=[('sent', 'Sent Successfully'), ('pending', 'Pending / Queued'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, verbose_name='Error Details (if failed)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='loyalty.patientloyaltyprofile', verbose_name='Patient Profile')),
            ],
            options={
                'verbose_name': 'Loyalty Notification Log',
                'verbose_name_plural': 'Loyalty Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='patientloyaltyprofile',
            constraint=models.UniqueConstraint(fields=('normalized_phone', 'program'), name='unique_patient_per_loyalty_program'),
        ),
    ]
