# Generated by Django 5.2.3 on 2026-09-01 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_checked_in_at_and_more'),
        ('loyalty', '0001_initial'),
        ('main', '0023_service_short_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='require_payment_verification',
            field=models.BooleanField(default=False, help_text='Option A (Unchecked): Treatment completed + Receptionist verified. Option B (Checked): Treatment completed + Payment completed + Receptionist verified.', verbose_name='Require Payment Completion Before Loyalty Verification'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='new_progress',
            field=models.PositiveIntegerField(default=0, verbose_name='New Progress'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='previous_progress',
            field=models.PositiveIntegerField(default=0, verbose_name='Previous Progress'),
        ),
        migrations.CreateModel(
            name='LoyaltyVerificationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=200, verbose_name='Treatment / Service Name')),
                ('decision', models.CharField(choices=[('approved', 'Loyalty Progress Approved (+1 Visit)'), ('rejected', 'Marked Not Eligible (0 Progress)'), ('overridden', 'Admin Override / Adjustment')], db_index=True, max_length=20, verbose_name='Decision')),
                ('previous_progress', models.PositiveIntegerField(default=0, verbose_name='Previous Progress')),
                ('new_progress', models.PositiveIntegerField(default=0, verbose_name='New Progress')),
                ('reward_unlocked', models.BooleanField(default=False, verbose_name='Triggered Reward Unlock')),
                ('payment_status_at_verification', models.CharField(blank=True, max_length=30, verbose_name='Payment Status at Decision')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='Ineligibility / Rejection Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Staff Notes')),
                ('verified_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Verified At')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_verification_logs', to='appointments.appointment', verbose_name='Appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='loyalty.patientloyaltyprofile', verbose_name='Patient Profile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service', verbose_name='Service')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Verified By (Staff)')),
            ],
            options={
                'verbose_name': 'Loyalty Verification Audit Log',
                'verbose_name_plural': 'Loyalty Verification Audit Logs',
                'ordering': ['-verified_at'],
            },
        ),
    ]
