# Generated by Django 5.2.3 on 2026-09-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_loyaltyprogram_require_payment_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='description_en',
            field=models.TextField(blank=True, default='Complete eligible dental visits and unlock exclusive savings on your care without any app or membership cards required.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='description_ne',
            field=models.TextField(blank=True, default='Complete eligible dental visits and unlock exclusive savings on your care without any app or membership cards required.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='name_en',
            field=models.CharField(default='CareFirst Smile Rewards', max_length=150, null=True, verbose_name='Program Name'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='name_ne',
            field=models.CharField(default='CareFirst Smile Rewards', max_length=150, null=True, verbose_name='Program Name'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='tagline_en',
            field=models.CharField(default='Your care deserves a little extra.', max_length=255, null=True, verbose_name='Program Tagline'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='tagline_ne',
            field=models.CharField(default='Your care deserves a little extra.', max_length=255, null=True, verbose_name='Program Tagline'),
        ),
    ]
