# Generated by Django 5.2.3 on 2026-08-16 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='Browser session or unique client token', max_length=255)),
                ('title', models.CharField(blank=True, default='New Consultation', max_length=255)),
                ('current_page', models.CharField(blank=True, default='/', max_length=500)),
                ('current_treatment', models.CharField(blank=True, help_text='Slug or title of treatment being viewed', max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('landing_page', models.CharField(blank=True, max_length=500)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Patient / Visitor'), ('assistant', 'CareFirst Assistant'), ('system', 'System Safety / Notification')], default='user', max_length=20)),
                ('content', models.TextField(help_text='Message body (safe sanitized markdown or text)')),
                ('intent', models.CharField(blank=True, db_index=True, help_text='Detected intent category', max_length=100)),
                ('quick_actions', models.JSONField(blank=True, default=list, help_text='List of quick suggestion action buttons')),
                ('cards', models.JSONField(blank=True, default=list, help_text='Structured cards (Treatment, Pricing Estimate, WhatsApp, Appointment)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Execution metadata (provider used, tokens, safety status)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(blank=True, db_index=True, max_length=100)),
                ('treatment', models.CharField(blank=True, db_index=True, max_length=150)),
                ('action', models.CharField(choices=[('answer', 'Answer Provided'), ('pricing', 'Pricing Estimated'), ('treatment_view', 'Treatment Viewed'), ('appointment_started', 'Appointment Booking Started'), ('appointment_completed', 'Appointment Successfully Submitted'), ('whatsapp_clicked', 'WhatsApp Consultation Clicked'), ('call_clicked', 'Direct Phone Call Clicked'), ('emergency_alerted', 'Emergency Safety Alerted')], db_index=True, max_length=50)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Chat Interaction',
                'verbose_name_plural': 'Chat Interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('positive', 'Helpful 👍'), ('negative', 'Not Helpful 👎')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Optional patient review / what they were looking for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='chatbot.chatmessage')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Chatbot Feedback',
                'verbose_name_plural': 'Chatbot Feedback Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('category', models.CharField(blank=True, default='general', max_length=100)),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Occurrences of this or similar unanswered inquiry')),
                ('notes', models.TextField(blank=True, help_text='Staff notes or draft answer')),
                ('status', models.CharField(choices=[('new', 'New / Pending Review'), ('reviewed', 'Reviewed'), ('added_to_faq', 'Added to Official FAQ'), ('ignored', 'Ignored / Invalid')], db_index=True, default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Unanswered Question',
                'verbose_name_plural': 'Unanswered Questions',
                'ordering': ['-frequency', '-created_at'],
            },
        ),
    ]
