# Generated by Django 5.2.3 on 2026-07-12 05:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('excerpt', models.TextField(help_text='A short summary of the post', max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(default='Carefirst Dental Clinic Team', max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reading_time', models.CharField(default='5 min read', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this as the main featured article')),
                ('is_popular', models.BooleanField(default=False, help_text='Show this in the Popular Articles section')),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogs.category')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
