# Generated by Django 5.2.3 on 2026-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.TextField(help_text='A short summary of the post', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_ne',
            field=models.TextField(help_text='A short summary of the post', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reading_time_en',
            field=models.CharField(default='5 min read', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reading_time_ne',
            field=models.CharField(default='5 min read', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ne',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
