# Generated by Django 5.2.3 on 2026-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_category_name_en_category_name_ne_post_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description (defaults to excerpt if blank)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title (defaults to title if blank)', max_length=200),
        ),
    ]
