# Generated by Django 5.2.3 on 2026-07-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(help_text='e.g. Chief Dental Surgeon', max_length=120)),
                ('specialty', models.CharField(choices=[('general', 'General Dentistry'), ('cosmetic', 'Cosmetic Dentistry'), ('orthodontics', 'Orthodontics'), ('implants', 'Dental Implants'), ('endodontics', 'Endodontics / Root Canal'), ('pediatric', 'Pediatric Dentistry'), ('oral_surgery', 'Oral Surgery'), ('periodontics', 'Periodontics')], default='general', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('bio', models.TextField(blank=True)),
                ('qualifications', models.CharField(blank=True, help_text='e.g. BDS, MDS, FICOI', max_length=255)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('certifications', models.TextField(blank=True, help_text='One per line')),
                ('languages', models.CharField(blank=True, help_text='e.g. English, Nepali, Hindi', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['order', 'name'],
            },
        ),
    ]
