# Generated by Django 5.2.3 on 2026-07-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('preventive', 'Preventive'), ('restorative', 'Restorative'), ('cosmetic', 'Cosmetic'), ('orthodontics', 'Orthodontics'), ('implants', 'Implants'), ('diagnostics', 'Diagnostics'), ('endodontics', 'Endodontics'), ('oral-surgery', 'Oral Surgery'), ('prosthodontics', 'Prosthodontics'), ('periodontal', 'Periodontal Care')], default='general', max_length=50)),
                ('category_label', models.CharField(help_text='e.g. GENERAL CARE', max_length=50)),
                ('icon', models.CharField(help_text='Bootstrap icon class, e.g. bi-tooth', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Image for the service card', null=True, upload_to='services/')),
                ('is_popular', models.BooleanField(default=False)),
                ('features', models.TextField(blank=True, help_text='One feature per line (for the checkmark list)')),
                ('starting_price', models.CharField(blank=True, help_text='e.g. 1,000', max_length=50)),
                ('custom_template', models.CharField(blank=True, help_text='e.g. services/dental_implants.html. If blank, generic template is used.', max_length=200, null=True)),
                ('detail_content', models.TextField(blank=True, help_text='Content for the generic service detail page')),
                ('detail_image', models.ImageField(blank=True, help_text='Hero image for the generic detail page', null=True, upload_to='services/details/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
