# Generated by Django 5.2.3 on 2026-07-12 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_alter_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pricing Category',
                'verbose_name_plural': 'Pricing Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(help_text='e.g. 1,000 - 2,500', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.pricingcategory')),
            ],
            options={
                'verbose_name': 'Pricing Item',
                'verbose_name_plural': 'Pricing Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
