# Generated by Django 5.2.3 on 2026-07-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pricingcategory_pricingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Dashain Mega Offer', max_length=200)),
                ('description', models.TextField(help_text='Short description of the offer')),
                ('start_date', models.DateTimeField(help_text='When the offer should start appearing')),
                ('end_date', models.DateTimeField(help_text='When the offer should stop appearing')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to instantly hide the offer regardless of dates')),
                ('button_text', models.CharField(default='Book Now', max_length=50)),
                ('button_link', models.CharField(default='/contact/#book', max_length=200)),
            ],
            options={
                'verbose_name': 'Special Offer',
                'verbose_name_plural': 'Special Offers',
                'ordering': ['-start_date'],
            },
        ),
    ]
