# Generated by Django 5.2.3 on 2026-07-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(blank=True, help_text='Promotional banner image for the popup', null=True, upload_to='offers/'),
        ),
    ]
