# Generated by Django 5.2.3 on 2026-07-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_specialoffer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='badge_text',
            field=models.CharField(blank=True, help_text='e.g. SPECIAL DASHAIN OFFER', max_length=50),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='features',
            field=models.TextField(blank=True, help_text='Format: Title | Description (one per line). e.g. Safe & Painless | Advanced tech with gentle techniques.'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='highlight_text',
            field=models.CharField(blank=True, help_text='e.g. 20% OFF', max_length=50),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='sub_text',
            field=models.CharField(blank=True, help_text='e.g. ON TEETH WHITENING & SCALING', max_length=150),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='button_text',
            field=models.CharField(default='Book Appointment Now', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='description',
            field=models.TextField(help_text='Short description of the offer (Used for Top Bar)'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(blank=True, help_text='Promotional banner image for the popup right side', null=True, upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='title',
            field=models.CharField(help_text='e.g. Dashain Mega Offer (Used for admin and Top Bar)', max_length=200),
        ),
    ]
