# Generated by Django 5.2.3 on 2026-07-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_specialoffer_badge_text_specialoffer_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certifications_en',
            field=models.TextField(blank=True, help_text='One per line', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='certifications_ne',
            field=models.TextField(blank=True, help_text='One per line', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='designation_en',
            field=models.CharField(help_text='e.g. Chief Dental Surgeon', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='designation_ne',
            field=models.CharField(help_text='e.g. Chief Dental Surgeon', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications_en',
            field=models.CharField(blank=True, help_text='e.g. BDS, MDS, FICOI', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications_ne',
            field=models.CharField(blank=True, help_text='e.g. BDS, MDS, FICOI', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricingcategory',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pricingcategory',
            name='name_ne',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pricingitem',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricingitem',
            name='name_ne',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pricingitem',
            name='price_en',
            field=models.CharField(help_text='e.g. 1,000 - 2,500', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingitem',
            name='price_ne',
            field=models.CharField(help_text='e.g. 1,000 - 2,500', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='category_label_en',
            field=models.CharField(help_text='e.g. GENERAL CARE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='category_label_ne',
            field=models.CharField(help_text='e.g. GENERAL CARE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='detail_content_en',
            field=models.TextField(blank=True, help_text='Content for the generic service detail page', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='detail_content_ne',
            field=models.TextField(blank=True, help_text='Content for the generic service detail page', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='features_en',
            field=models.TextField(blank=True, help_text='One feature per line (for the checkmark list)', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='features_ne',
            field=models.TextField(blank=True, help_text='One feature per line (for the checkmark list)', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ne',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='badge_text_en',
            field=models.CharField(blank=True, help_text='e.g. SPECIAL DASHAIN OFFER', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='badge_text_ne',
            field=models.CharField(blank=True, help_text='e.g. SPECIAL DASHAIN OFFER', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='button_text_en',
            field=models.CharField(default='Book Appointment Now', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='button_text_ne',
            field=models.CharField(default='Book Appointment Now', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='description_en',
            field=models.TextField(help_text='Short description of the offer (Used for Top Bar)', null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='description_ne',
            field=models.TextField(help_text='Short description of the offer (Used for Top Bar)', null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='features_en',
            field=models.TextField(blank=True, help_text='Format: Title | Description (one per line). e.g. Safe & Painless | Advanced tech with gentle techniques.', null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='features_ne',
            field=models.TextField(blank=True, help_text='Format: Title | Description (one per line). e.g. Safe & Painless | Advanced tech with gentle techniques.', null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='highlight_text_en',
            field=models.CharField(blank=True, help_text='e.g. 20% OFF', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='highlight_text_ne',
            field=models.CharField(blank=True, help_text='e.g. 20% OFF', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='sub_text_en',
            field=models.CharField(blank=True, help_text='e.g. ON TEETH WHITENING & SCALING', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='sub_text_ne',
            field=models.CharField(blank=True, help_text='e.g. ON TEETH WHITENING & SCALING', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='title_en',
            field=models.CharField(help_text='e.g. Dashain Mega Offer (Used for admin and Top Bar)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='title_ne',
            field=models.CharField(help_text='e.g. Dashain Mega Offer (Used for admin and Top Bar)', max_length=200, null=True),
        ),
    ]
