# Generated by Django 5.2.3 on 2026-07-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutpagesettings_branch_clinicgallery_corevalue_faq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone', models.CharField(default='984-8631371', max_length=50)),
                ('secondary_phone', models.CharField(blank=True, default='9765318101', max_length=50)),
                ('whatsapp_number', models.CharField(default='9779848631371', help_text='Number with country code for WhatsApp link (e.g. 9779848631371)', max_length=50)),
                ('email', models.EmailField(default='nikodentalandaesthetics@gmail.com', max_length=254)),
                ('address', models.CharField(default='Koteshwor-32, Kathmandu', max_length=200)),
                ('landmark', models.TextField(default='200m ahead of Police Office towards Mahadevsthan, exactly in front of Sanima Bank')),
                ('google_maps_iframe_url', models.URLField(blank=True, help_text="The 'src' URL from Google Maps Embed iframe", max_length=1000)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('working_hours_weekdays', models.CharField(default='Sun - Fri: 9:00 AM - 7:00 PM', max_length=100)),
                ('working_hours_weekend', models.CharField(default='Saturday: Closed / Emergencies', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
