# Generated by Django 5.2.3 on 2026-07-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_service_meta_description_service_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOFAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'SEO FAQ Categories',
            },
        ),
        migrations.CreateModel(
            name='SEOFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('primary_keyword', models.CharField(blank=True, max_length=200)),
                ('secondary_keywords', models.TextField(blank=True, help_text='Comma separated')),
                ('search_intent', models.CharField(blank=True, choices=[('Informational', 'Informational'), ('Commercial', 'Commercial'), ('Transactional', 'Transactional'), ('Local', 'Local')], max_length=100)),
                ('suggested_internal_links', models.TextField(blank=True)),
                ('related_services', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='main.seofaqcategory')),
            ],
            options={
                'verbose_name': 'SEO FAQ',
                'verbose_name_plural': 'SEO FAQs',
                'ordering': ['order'],
            },
        ),
    ]
