# Generated by Django 5.2.3 on 2026-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_seofaqcategory_seofaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicgallery',
            name='category',
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_number',
            field=models.CharField(blank=True, help_text='Nepal Medical Council Number (e.g. 31229)', max_length=50, null=True),
        ),
    ]
