# Generated by Django 5.2.3 on 2026-08-05 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_clinicgallery_category_doctor_nmc_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('google_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='Never synced', max_length=30)),
                ('sync_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Business',
                'verbose_name_plural': 'Google Business',
            },
        ),
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_review_id', models.CharField(max_length=500, unique=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_photo', models.URLField(blank=True, max_length=1000)),
                ('author_url', models.URLField(blank=True, max_length=1000)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review_text', models.TextField(blank=True)),
                ('relative_time', models.CharField(blank=True, max_length=100)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.googlebusiness')),
            ],
            options={
                'verbose_name': 'Google Review',
                'verbose_name_plural': 'Google Reviews',
                'ordering': ['-publish_time', '-created_at'],
            },
        ),
    ]
