# Generated by Django 5.2.3 on 2026-08-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_googlebusiness_googlereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='treatment',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='treatment_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='treatment_ne',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
