# Generated by Django 5.2.3 on 2026-08-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_testimonial_treatment_testimonial_treatment_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Pragatinagar Road, Shankhamul-31, Kathmandu 44600', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='carefirstdentalclinic@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landmark',
            field=models.TextField(default='Shankhamul / New Baneshwor area'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone',
            field=models.CharField(default='980-7464136', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_phone',
            field=models.CharField(blank=True, default='01-5916886', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='9779807464136', help_text='Number with country code for WhatsApp link (e.g. 9779807464136)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='working_hours_weekdays',
            field=models.CharField(default='Mon - Sun: 7:30 AM - 7:30 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='working_hours_weekend',
            field=models.CharField(default='Mon - Sun: 7:30 AM - 7:30 PM', max_length=100),
        ),
    ]
