# Generated by Django 5.2.3 on 2026-08-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_sitesettings_address_alter_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlereview',
            name='google_review_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
