# Generated by Django 5.2.3 on 2026-08-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_heroslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Patient Story / Testimonial', 'verbose_name_plural': 'Patient Stories & Testimonials'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='clinical_journey',
            field=models.TextField(blank=True, help_text='Procedure performed by Dr. Subash Banjade and clinical team'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='headline',
            field=models.CharField(blank=True, help_text='Editorial story headline (e.g. A confident smile, restored.)', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='initial_concern',
            field=models.TextField(blank=True, help_text="Patient's initial dental concern/problem"),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='outcome',
            field=models.TextField(blank=True, help_text='Final aesthetic and clinical outcome'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='tag_color',
            field=models.CharField(choices=[('default', 'Teal (Standard)'), ('cosmetic', 'Purple (Cosmetic)'), ('whitening', 'Sky Blue (Whitening)'), ('implant', 'Emerald (Implants)')], default='default', help_text='Badge color styling', max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, help_text='Patient portrait or clinical transformation image', null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review',
            field=models.TextField(help_text='Patient quote or story excerpt'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review_en',
            field=models.TextField(help_text='Patient quote or story excerpt', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review_ne',
            field=models.TextField(help_text='Patient quote or story excerpt', null=True),
        ),
    ]
