# Generated by Django 5.2.3 on 2026-08-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short 1-2 sentence description for homepage & listing cards'),
        ),
    ]
