# Generated by Django 5.2.3 on 2026-08-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_service_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seofaq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seofaq',
            name='answer_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seofaq',
            name='question_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seofaq',
            name='question_ne',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seofaqcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seofaqcategory',
            name='description_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seofaqcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seofaqcategory',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
