# Generated by Django 5.2.3 on 2026-08-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_seofaq_answer_en_seofaq_answer_ne_seofaq_question_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Short 1-2 sentence description for homepage & listing cards', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ne',
            field=models.TextField(blank=True, help_text='Short 1-2 sentence description for homepage & listing cards', null=True),
        ),
    ]
