# Generated by Django 5.2.3 on 2026-09-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_service_short_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
    ]
