# Generated by Django 5.2.3 on 2026-09-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_sitesettings_tiktok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_ne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(blank=True, help_text='e.g. Modern Operatory & Care', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_ne',
            field=models.CharField(blank=True, help_text='e.g. Modern Operatory & Care', max_length=200, null=True),
        ),
    ]
