# Generated by Django 5.2.3 on 2026-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('preferred_date', models.DateField(verbose_name='Preferred Date')),
                ('preferred_time', models.CharField(blank=True, choices=[('', 'Any Time'), ('morning', 'Morning (9AM - 12PM)'), ('afternoon', 'Afternoon (12PM - 4PM)'), ('evening', 'Evening (4PM - 7PM)')], max_length=50, verbose_name='Preferred Time')),
                ('treatment', models.CharField(blank=True, choices=[('', 'General Check-up & Consultation'), ('cleaning', 'Scaling & Polishing'), ('filling', 'Dental Filling'), ('rct', 'Root Canal Treatment'), ('extraction', 'Tooth Extraction'), ('implants', 'Dental Implants'), ('braces', 'Braces / Orthodontics'), ('other', 'Other / Not Sure')], max_length=50, verbose_name='Treatment')),
                ('message', models.TextField(blank=True, verbose_name='Message / Special Requirements')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-created_at'],
            },
        ),
    ]
