# Generated by Django 6.0.7 on 2026-07-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiriesDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Inquiries Dashboard',
                'verbose_name_plural': 'Inquiries Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appointments.appointment',),
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'All Appointments'},
        ),
    ]
