# Generated by Django 5.2.3 on 2026-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_inquiriesdashboard_alter_appointment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(max_length=50, verbose_name='Inquiry Type')),
                ('inquiry_id', models.IntegerField(verbose_name='Inquiry ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='Patient Name')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('message_text', models.TextField(verbose_name='Message Text')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'WhatsApp Notification',
                'verbose_name_plural': 'WhatsApp Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
