# Generated by Django 5.2.3 on 2026-08-16 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_branch_appointment_doctor'),
        ('main', '0017_alter_sitesettings_address_alter_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(blank=True, db_index=True, help_text='Human-readable reference ID e.g. CF-2026-000123', max_length=50, null=True, unique=True, verbose_name='Appointment Request ID'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'Book a Consultation'), ('treatment', 'Direct Treatment Visit'), ('follow_up', 'Follow-up / Routine Check'), ('checkup', 'General Dental Check-up')], default='consultation', max_length=40, verbose_name='Appointment Type'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='chat_used',
            field=models.BooleanField(default=False, verbose_name='Booked via AI Chatbot'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimated_amount',
            field=models.CharField(blank=True, max_length=100, verbose_name='Informational Price Estimate'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimator_used',
            field=models.BooleanField(default=False, verbose_name='Booked via Cost Estimator'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='internal_note',
            field=models.TextField(blank=True, verbose_name='Staff Internal Notes (Hidden from Patient)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='landing_page',
            field=models.CharField(blank=True, max_length=500, verbose_name='Landing Page URL'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_date',
            field=models.DateField(blank=True, null=True, verbose_name='Original Requested Date'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='original_time',
            field=models.CharField(blank=True, max_length=50, verbose_name='Original Requested Time'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pricing_option',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pricing Option / Material'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Tooth / Unit Quantity'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='referrer',
            field=models.CharField(blank=True, max_length=500, verbose_name='Referrer URL'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reschedule Reason'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='main.service', verbose_name='Selected Service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Content'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Term'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, verbose_name='Patient Notes / Special Requirements'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('', 'Flexible / Any Time'), ('morning', 'Morning (7:30 AM - 12:00 PM)'), ('afternoon', 'Afternoon (12:00 PM - 4:00 PM)'), ('evening', 'Evening (4:00 PM - 7:30 PM)')], max_length=50, verbose_name='Preferred Time Slot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('new', 'New Request'), ('pending', 'Pending Staff Review'), ('confirmed', 'Confirmed Slot'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed Visit'), ('no_show', 'No Show')], db_index=True, default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='treatment',
            field=models.CharField(blank=True, choices=[('', 'General Dental Consultation'), ('scaling-and-polishing', 'Scaling & Polishing'), ('dental-filling', 'Dental Filling'), ('root-canal-treatment', 'Root Canal Treatment (RCT)'), ('tooth-extraction', 'Tooth Extraction & Wisdom Teeth'), ('dental-implants', 'Dental Implants'), ('orthodontic-treatment-braces', 'Braces & Clear Aligners'), ('teeth-whitening', 'Professional Teeth Whitening'), ('crowns-and-bridges', 'Crowns & Bridges / Veneers'), ('periodontal-treatment-gum', 'Gum Care & Periodontal Therapy'), ('dentures', 'Complete & Partial Dentures'), ('digital-dental-x-ray', 'Digital RVG Dental X-Ray'), ('other', 'Other / Unsure')], max_length=100, verbose_name='Treatment Category'),
        ),
        migrations.CreateModel(
            name='AppointmentFunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('STARTED', 'Funnel Started'), ('TREATMENT_SELECTED', 'Treatment Selected'), ('TYPE_SELECTED', 'Appointment Type Selected'), ('DATE_SELECTED', 'Date Selected'), ('TIME_SELECTED', 'Time Selected'), ('DETAILS_STARTED', 'Patient Details Form Started'), ('REVIEW_VIEWED', 'Summary Review Viewed'), ('SUBMITTED', 'Successfully Submitted'), ('ABANDONED', 'Funnel Abandoned'), ('CONFIRMED', 'Confirmed by Staff'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed Visit')], db_index=True, max_length=50)),
                ('treatment_slug', models.CharField(blank=True, max_length=150)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Funnel Event',
                'verbose_name_plural': 'Funnel Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
