# Generated by Django 5.2.3 on 2026-09-01 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_appointment_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checked In At'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='loyalty_rejection_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Loyalty Ineligibility Reason'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='loyalty_status',
            field=models.CharField(choices=[('none', 'Not Applicable'), ('awaiting_verification', 'Awaiting Loyalty Verification'), ('verified', 'Loyalty Progress Granted (+1)'), ('not_eligible', 'Marked Not Eligible')], db_index=True, default='none', max_length=30, verbose_name='Loyalty Verification Status'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='loyalty_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Loyalty Verified At'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='loyalty_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Loyalty Verified By'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Payment Completed'), ('waived', 'Payment Waived / Free Checkup')], db_index=True, default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('new', 'New Request'), ('pending', 'Pending Staff Review'), ('confirmed', 'Confirmed Slot'), ('checked_in', 'Patient Checked In / Arrived'), ('completed', 'Completed Visit'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='new', max_length=20, verbose_name='Status'),
        ),
    ]
