# Generated by Django 5.2.3 on 2026-09-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_checked_in_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, help_text='Cryptographically secure random token for patient access without login', max_length=100, null=True, unique=True, verbose_name='Secure Access Token'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking_id',
            field=models.CharField(blank=True, db_index=True, help_text='Human-readable unique reference e.g. CF-APT-20260902-A7X92', max_length=60, null=True, unique=True, verbose_name='Booking Reference ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(blank=True, db_index=True, help_text='Legacy reference ID compatible with booking_id', max_length=60, null=True, unique=True, verbose_name='Appointment Request ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('checked_in', 'Patient Checked In / Arrived'), ('completed', 'Completed Visit'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('new', 'New Request')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Update At'),
        ),
    ]
