# Generated by Django 5.2.3 on 2026-09-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_access_token_appointment_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_channel',
            field=models.CharField(blank=True, default='email', max_length=50, verbose_name='Reminder Channel'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Reminders Sent'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False, verbose_name='24h Reminder Sent'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reminder Sent At'),
        ),
    ]
