# Generated by Django 5.2.3 on 2026-07-16 03:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_aboutpagesettings_branch_clinicgallery_corevalue_faq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('home_hero', 'Homepage Hero Banner'), ('home_video', 'Homepage Hero Video'), ('service_hero', 'Service Hero Images'), ('about_banner', 'About Page Banner'), ('gallery_banner', 'Gallery Banner'), ('contact_banner', 'Contact Banner'), ('blog_banner', 'Blog Banner'), ('seasonal', 'Seasonal Campaign Banner'), ('popup', 'Popup Banner'), ('promotional', 'Promotional Banner')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ne', models.CharField(blank=True, max_length=200, null=True)),
                ('desktop_image', models.ImageField(blank=True, null=True, upload_to='banners/desktop/')),
                ('tablet_image', models.ImageField(blank=True, null=True, upload_to='banners/tablet/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_text_en', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_text_ne', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_url', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('schedule_start', models.DateTimeField(blank=True, null=True)),
                ('schedule_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConnectedSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('access_token', models.TextField(blank=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ne', models.CharField(max_length=100, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ne', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialImportQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('video_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('imported_videos', models.PositiveIntegerField(default=0)),
                ('failed_videos', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ne', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Video Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ne', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ne', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DownloadableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ne', models.CharField(max_length=200, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='documents/thumbnails/')),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
                ('download_counter', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_center.documentcategory')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ne', models.CharField(max_length=200, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/albums/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='media_center.gallerycategory')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ne', models.CharField(max_length=200, null=True)),
                ('short_description', models.TextField(blank=True)),
                ('short_description_en', models.TextField(blank=True, null=True)),
                ('short_description_ne', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='gallery/images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='media_center.galleryalbum')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='media_center.gallerycategory')),
                ('related_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.branch')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ne', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('video_id', models.CharField(help_text='ID from the platform', max_length=100)),
                ('video_url', models.URLField()),
                ('embed_url', models.URLField(blank=True)),
                ('thumbnail', models.URLField(blank=True, help_text='External URL to the thumbnail')),
                ('short_description', models.TextField(blank=True)),
                ('short_description_en', models.TextField(blank=True, null=True)),
                ('short_description_ne', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_title_ne', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_description_en', models.TextField(blank=True, null=True)),
                ('seo_description_ne', models.TextField(blank=True, null=True)),
                ('related_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.branch')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='media_center.videocategory')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='media_center.videoplaylist')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialSyncSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20, unique=True)),
                ('enable_auto_sync', models.BooleanField(default=False)),
                ('sync_frequency', models.CharField(choices=[('30m', 'Every 30 Minutes'), ('1h', 'Every Hour'), ('6h', 'Every 6 Hours'), ('24h', 'Daily')], default='24h', max_length=10)),
                ('max_videos_to_import', models.PositiveSmallIntegerField(default=10)),
                ('auto_publish', models.BooleanField(default=True)),
                ('auto_generate_thumbnail', models.BooleanField(default=True)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.branch')),
                ('default_related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service')),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_center.videocategory')),
                ('default_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_center.videoplaylist')),
            ],
        ),
    ]
