# Generated by Django 5.2.3 on 2026-07-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0002_remove_video_embed_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
