# Generated by Django 5.2.3 on 2026-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0003_delete_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, help_text='Can be left blank if you provide the full Video URL below', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste the full video URL here to auto-extract the ID'),
        ),
    ]
