# Generated by Django 5.2.3 on 2026-07-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0004_alter_video_video_id_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Optional: Paste the raw iframe embed code directly from YouTube/Facebook'),
        ),
    ]
