# Generated by Django 5.2.3 on 2026-07-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0005_video_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='External URL to the thumbnail (auto-fetched)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a local image for the thumbnail (overrides the auto-fetched URL)', null=True, upload_to='video_thumbnails/'),
        ),
    ]
