# Generated by Django 5.2.3 on 2026-07-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0006_video_thumbnail_url_alter_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadabledocument',
            name='category',
        ),
        migrations.RemoveField(
            model_name='galleryalbum',
            name='category',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='album',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='related_branch',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='related_service',
        ),
        migrations.DeleteModel(
            name='SocialImportQueue',
        ),
        migrations.DeleteModel(
            name='DocumentCategory',
        ),
        migrations.DeleteModel(
            name='DownloadableDocument',
        ),
        migrations.DeleteModel(
            name='GalleryAlbum',
        ),
        migrations.DeleteModel(
            name='GalleryCategory',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
