# Generated by Django 6.0.7 on 2026-08-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0007_remove_downloadabledocument_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram')], max_length=20),
        ),
    ]
