# Generated by Django 5.2.3 on 2026-08-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0008_alter_video_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook')], default='youtube', max_length=20),
        ),
    ]
